var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Français",
  title: "Botly Studio",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Tout supprimer",
  settings: "Paramètres",
  documentation: "Documentation",
  reportBug: "Signaler un problème",
  examples: "Exemples",
  /* Settings */
  compilerLocation: "Emplacement du compilateur",
  compilerLocationDefault: "Emplacement par défaut",
  sketchFolder: "Emplacement du fichier",
  sketchFolderDefault: "Emplacement fichier par défaut",
  arduinoBoard: "Carte Arduino",
  arduinoBoardDefault: "Carte Arduino inconnue",
  comPort: "Port Série",
  comPortDefault: "COM3",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Langue",
  languageDefault: "Langue inconnue",
  sketchName: "Nom_de_projet",
  /* Arduino console output */
  arduinoOpMainTitle: "Console Arduno IDE",
  arduinoOpWaiting: "Chargement de la reponse Arduino IDE ...",
  arduinoOpUploadedTitle: "Téléversement terminé",
  arduinoOpVerifiedTitle: "Compilation terminée",
  arduinoOpOpenedTitle: "Sketch ouvert dans l'IDE",
  arduinoOpOpenedBody: "Le Sketch est normalement ouvert dans l'IDE",
  arduinoOpErrorUpVerTitle: "La compilation ou le téléversement à échoué",
  arduinoOpErrorSketchTitle: "Erreur : le nom du projet n'est pas conforme",
  arduinoOpErrorFlagTitle: "",
  arduinoOpErrorFlagPrefTitle: "",
  arduinoOpErrorIdeDirTitle: "Erreur: le chemin d'accès au compilateur n'est pas valide",
  arduinoOpErrorIdeDirBody: "Erreur: le chemin d'accès au compilateur n'est pas valide",
  arduinoOpErrorIdeOptionTitle: "",
  arduinoOpErrorIdeOptionBody: "L'option de démarage de l'IDE n'a pas encore été défini.<br>" +
                               "Veuillez selectionner une option dans les paramètres.",
  arduinoOpErrorIdePortTitle: "Aucun port série disponible",
  arduinoOpErrorIdePortBody: "Erreur : Le port série ne réponds pas",
  arduinoOpErrorIdeBoardTitle: "",
  arduinoOpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody: "",
  noServerNoLangBody: "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "Téléversement...",
  uploadSketch: "Téléverser",
  verifyingSketch: "Vérification...",
  verifySketch: "Verifier",
  openingSketch: "Ouverture...",
  openSketch: "Ouvrir dans l'IDE",
  notImplemented: "Echec",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  arduinoSourceCode: "Code Source",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catAudio: "Audio",
  catScott: "Botly",
  catMotors: "Moteurs",
  catComms: "Comms",
};
